server {
  port = 8080
  // time before shutdown is initiated
  preWait = "5s"
}

ediAdapter {
  scope = "api://dev-gcp.helsemelding.edi-adapter/.default"
}

poller {
  herId = "${POLLER_HER_ID:-8142519}"
  fetchLimit = "${POLLER_FETCH_LIMIT:-10}"
  batchSize = "${POLLER_BATCH_SIZE:-5}"
  scheduleInterval = "${POLLER_SCHEDULE_INTERVAL:-2}m"
}

kafka {
  groupId = "helsemelding.inbound-message-service"
  bootstrapServers = "${KAFKA_BROKERS:-http://localhost:9092}"
  securityProtocol = "SSL"
  keystoreType = "PKCS12"
  keystoreLocation = "${KAFKA_KEYSTORE_PATH:-}"
  keystorePassword = "${KAFKA_CREDSTORE_PASSWORD:-}"
  truststoreType = "JKS"
  truststoreLocation = "${KAFKA_TRUSTSTORE_PATH:-}"
  truststorePassword = "${KAFKA_CREDSTORE_PASSWORD:-}"
  topics {
    dialogMessage = "helsemelding.dialog.in.xml"
  }
}
